# jaxlib wants clang on all platforms
c_compiler:
- clang
cxx_compiler:
- clangxx
# in the global pinning on linux, {c,cxx}_compiler_version
# is mixed with CUDA and zipped with c_stdlib_version
c_compiler_version:
- '20'
- '20'                  # [linux]
cxx_compiler_version:
- '20'
- '20'                  # [linux]
c_stdlib_version:       # [linux]
- '2.17'                # [linux]
- '2.17'                # [linux]

github_actions_labels:
- namespace-profile-16cpu-on-linux-64       # [linux64]
- namespace-profile-8cpu-on-linux-aarch64   # [linux and aarch64]
- namespace-profile-12cpu-on-osx-arm64      # [osx]
