github_actions_labels:
- cirun-openstack-cpu-large
c_compiler_version:     # [aarch64]
  - '13'                # [aarch64]
  - '13'                # [aarch64]
cxx_compiler_version:   # [aarch64]
  - '13'                # [aarch64]
  - '13'                # [aarch64]
