c_stdlib_version:          # [osx and x86_64]
- '10.15'                  # [osx and x86_64]
github_actions_labels:
- cirun-openstack-cpu-large
c_compiler_version:    # [linux]
  - '13'               # [linux]
cxx_compiler_version:  # [linux]
  - '13'               # [linux]
