{% set version = "0.1.42" %}
{% set name = "jaxlib" %}

{% set pyver = "cp{}{}".format(PY_VER[0], PY_VER[2]) %}
{% set platform = "manylinux2010_x86_64" %}  # [linux]
{% set platform = "macosx_10_9_x86_64" %}  # [osx]

# {distribution}-{version}(-{build tag})?-{python tag}-{abi tag}-{platform tag}.whl.
{% set fn = "{}-{}-{}-none-{}.whl".format(name, version, pyver, platform) %}

package:
  name: jaxlib
  version: {{ version }}

source:
  fn: {{ fn }}
  url: https://pypi.io/packages/{{ pyver }}/{{ name[0] }}/{{ name }}/{{ fn }}
  sha256: 0ca99b7ecee52e7f0d5287e7917a8faebe55205c68694ff0076ac781478dede8  # [linux and py==36]
  sha256: 2bdc0651c272f69c4e54c36352ceda23bf6cb2e7c11d77f71e61e152ab95cee0  # [osx and py==36]

  sha256: 8027e741872eebd587d621d0a6ceaf07c6dea77a92b75602b904c0f01c9d5db4  # [linux and py==37]
  sha256: 476da8512706f46b1ec118579530d81d743e9752f846555e5d649365e76607f5  # [osx and py==37]

  sha256: 31908dfc68e48d4fa38a80a455bc87afa74c54b44cff547568d73438ddfa21fc  # [linux and py==38]
  sha256: 24a061a24b638e953a4e466f15313f4b7f74b22e304fd28679c94dc5ad9c1ade  # [osx and py==38]

build:
  number: 0
  skip: True  # [win or py2k]
  script: "{{ PYTHON }} -m pip install --no-deps -vv {{ fn }}"

requirements:
  host:
    - python
    - pip
  run:
    - python
    - absl-py
    - numpy >=1.12
    - protobuf >=3.6.0
    - scipy
    - six

test:
  requires:
    - pip
  commands:
    - pip check
  # imports:
    # cannot run the test b/c this is not really manylinux1 GLIBC_2.14
    # Google :-/
    # - jaxlib

about:
  home: http://github.com/google/jax
  license: Apache-2.0
  license_file: LICENSE
  summary: "Composable transformations of Python+NumPy programs: differentiate, vectorize, JIT to GPU/TPU, and more"

  dev_url: http://github.com/google/jax

extra:
  recipe-maintainers:
    - ericmjl
