{% set version = "0.4.35" %}
{% set name = "jaxlib" %}

{% set build = 3 %}

{% if cuda_compiler_version != "None" %}
{% set build = build + 200 %}
{% endif %}


package:
  name: jaxlib
  version: {{ version }}

source:
  url: https://github.com/google/jax/archive/jax-v{{ version }}.tar.gz
  sha256: 65e086708ae56670676b7b2340ad82b901d8c9993d1241a839c8990bdb8d6212
  patches:
      - patches/0000-Consolidated-build-fixes-for-XLA.patch  # [not win]
      - patches/0001-Add-missing-typename.patch  # [not win]

build:
  number: {{ build }}
  # s390x is missing bazel.
  skip: true  # [s390x or py<310]
  skip: true  # [skip_cuda_prefect and (gpu_variant or "").startswith('cuda')]
  string: cuda{{ cuda_compiler_version | replace('.', '') }}py{{ CONDA_PY }}h{{ PKG_HASH }}_{{ PKG_BUILDNUM }}  # [(gpu_variant or "").startswith('cuda')]
  string: cpu_py{{ CONDA_PY }}h{{ PKG_HASH }}_{{ PKG_BUILDNUM }}  # [(gpu_variant or "").startswith('cpu')]

requirements:
  build:
    - {{ compiler('c') }}
    - {{ compiler('cxx') }}
    - {{ compiler('cuda') }}  # [(gpu_variant or "").startswith('cuda')]
    - clang    # [win]
    - llvmdev  # [win]
    - lld      # [win]
    - python
    # https://github.com/jax-ml/jax/blob/jax-v0.4.35/build/build.py#L198
    - bazel >=6.5.0,<7
    - bazel-toolchain >=0.1.9  # [not win]
    - libabseil {{ libabseil }}
    - patch  # [not win]
    - libgrpc {{ libgrpc }}

  host:
    - cudnn {{ cudnn }}           # [(gpu_variant or "").startswith('cuda')]
    - nccl  {{ nccl }}            # [(gpu_variant or "").startswith('cuda')]
    - cuda-cupti-dev 12.4.127     # [(gpu_variant or "").startswith('cuda-12')]
    - cuda-cudart-dev 12.4.127    # [(gpu_variant or "").startswith('cuda-12')]
    - cuda-nvml-dev 12.4.127      # [(gpu_variant or "").startswith('cuda-12')]
    - cuda-nvtx-dev 12.4.127      # [(gpu_variant or "").startswith('cuda-12')]
    - cuda-nvcc-tools 12.4.131    # [(gpu_variant or "").startswith('cuda-12')]
    - libcublas-dev 12.4.5.8      # [(gpu_variant or "").startswith('cuda-12')]
    - libcusolver-dev 11.6.1.9    # [(gpu_variant or "").startswith('cuda-12')]
    - libcurand-dev 10.3.5.147    # [(gpu_variant or "").startswith('cuda-12')]
    - libcufft-dev 11.2.1.3       # [(gpu_variant or "").startswith('cuda-12')]
    - libcusparse-dev 12.3.1.170  # [(gpu_variant or "").startswith('cuda-12')]
    - python
    - pip
    - wheel
    - setuptools
    - numpy 2
    - python-build
    - libabseil {{ libabseil }}  # [not win]
    - openssl {{ openssl }}  # [not win]
    - nsync 1.24.0  # [not win]
    - snappy 1.2.1  # [not win]
    - double-conversion 3.1.5  # [not win]
    - jsoncpp 1.9.6  # [not win]
    - pybind11 2.13.6  # [not win]
    - libgrpc {{ libgrpc }}  # [not win]
    - libcurl {{ libcurl }}  # [not win]
    - zlib {{ zlib }}  # [not win]

  run:
    - python
    - numpy >=1.24
    - scipy >=1.10    # [py<312]
    - scipy >=1.11.1  # [py>=312]
    - ml_dtypes >=0.2.0
    - {{ pin_compatible('double-conversion', max_pin='x.x') }}
    - __cuda  # [(gpu_variant or "").startswith('cuda')]
    - cuda-nvcc-tools  # [(gpu_variant or "").startswith('cuda-12')]
  run_constrained:
    - jax >={{ version }}

test:
  files:
    - test_jaxlib.py
  requires:
    - pip
    - python
  commands:
    - pip check
    - python test_jaxlib.py
    - python -c "import importlib.metadata; assert importlib.metadata.version('jaxlib') == '{{ version }}'"
  imports:
    - jaxlib
    - jaxlib.xla_client

about:
  home: https://github.com/google/jax
  license: Apache-2.0
  license_file: LICENSE
  license_family: Apache
  summary: 'Composable transformations of Python+NumPy programs: differentiate, vectorize, JIT to GPU/TPU, and more'
  description: |
    jaxlib is the support library for JAX. While JAX itself is a pure Python package, jaxlib contains the binary (C/C++) parts of the library, including Python bindings, the XLA compiler, the PJRT runtime, and a handful of handwritten kernels.
  dev_url: https://github.com/google/jax
  doc_url: https://jax.readthedocs.io/

extra:
  recipe-maintainers:
    - ericmjl
    - xhochy
