{% set version = "0.6.1" %}
{% set build = 0 %}

{% if cuda_compiler_version != "None" %}
{% set build = build + 200 %}
{% endif %}


package:
  name: jaxlib
  version: {{ version }}

source:
  # only pull sources after upstream PyPI release...
  url: https://github.com/jax-ml/jax/archive/jax-v{{ version }}.tar.gz
  sha256: af179a4047d473059beebc4b9d09763e80d8f7dcf4ae75670bc3dd912c92d6f5
  patches:
    - patches/0001-Allow-for-custom-CUDA-build.patch
    - patches/0002-Consolidated-build-fixes-for-XLA.patch

build:
  number: {{ build }}
  skip: true  # [win or py<310]
  skip: true  # [cuda_compiler_version != "None" and aarch64]
  # Currently the GPU kernels (and their abseil includes) are not compatible with GCC 11
  skip: true  # [cuda_compiler_version == "11.8"]
  string: cuda{{ cuda_compiler_version | replace('.', '') }}py{{ CONDA_PY }}h{{ PKG_HASH }}_{{ PKG_BUILDNUM }}  # [cuda_compiler_version != "None"]
  string: cpu_py{{ CONDA_PY }}h{{ PKG_HASH }}_{{ PKG_BUILDNUM }}  # [cuda_compiler_version == "None"]

requirements:
  build:
    - {{ compiler('c') }}
    - {{ stdlib("c") }}
    - {{ compiler('cxx') }}
    - {{ compiler('cuda') }}                 # [cuda_compiler_version != "None"]
    - python                                 # [build_platform != target_platform]
    - cross-python_{{ target_platform }}     # [build_platform != target_platform]
    - numpy                                  # [build_platform != target_platform]
    - zlib                                   # [build_platform != target_platform]
    - unzip
    - rsync  # [(cuda_compiler_version or "").startswith("12")]
    # Keep bazel listed twice here to help the migrators track dependencies
    - bazel
    - bazel 7.*
    - bazel-toolchain >=0.3.0
    # need protoc
    - libprotobuf
    # needs protoc-gen-grpc
    - libgrpc
    # needs flatc
    - flatbuffers <2.0.6
    # list libabseil here to ensure pinning correctly
    - libabseil
    - sed
  host:
    - cudnn             # [cuda_compiler_version != "None"]
    - nccl              # [cuda_compiler_version != "None"]
    - cuda-cupti-dev    # [(cuda_compiler_version or "").startswith("12")]
    - cuda-cudart-dev   # [(cuda_compiler_version or "").startswith("12")]
    - cuda-nvml-dev     # [(cuda_compiler_version or "").startswith("12")]
    - cuda-nvtx-dev     # [(cuda_compiler_version or "").startswith("12")]
    - cuda-nvcc-tools   # [(cuda_compiler_version or "").startswith("12")]
    - libcublas-dev     # [(cuda_compiler_version or "").startswith("12")]
    - libcusolver-dev   # [(cuda_compiler_version or "").startswith("12")]
    - libcurand-dev     # [(cuda_compiler_version or "").startswith("12")]
    - libcufft-dev      # [(cuda_compiler_version or "").startswith("12")]
    - libcusparse-dev   # [(cuda_compiler_version or "").startswith("12")]
    - python
    - pip
    - numpy
    - setuptools
    - wheel
    - cuda-version {{ cuda_compiler_version }}  # [cuda_compiler_version != "None"]
    - python-build
    # list libabseil here to ensure pinning correctly
    - libabseil
    - flatbuffers <2.0.6
    - libgrpc
    - openssl
    - zlib
  run:
    - python
    - scipy >=1.9
    - ml_dtypes >=0.2.0
    - __cuda  # [cuda_compiler_version != "None"]
    - cuda-nvcc-tools   # [(cuda_compiler_version or "").startswith("12")]
    # Workaround for https://github.com/conda-forge/jaxlib-feedstock/pull/288#issuecomment-2511925904
    - libcublas-dev     # [(cuda_compiler_version or "").startswith("12")]
    - libcusolver-dev   # [(cuda_compiler_version or "").startswith("12")]
    - libcurand-dev     # [(cuda_compiler_version or "").startswith("12")]
    - cuda-cupti-dev    # [(cuda_compiler_version or "").startswith("12")]
    - libcufft-dev      # [(cuda_compiler_version or "").startswith("12")]
    - libcusparse-dev   # [(cuda_compiler_version or "").startswith("12")]
  run_constrained:
    - jax >={{ version }}

test:
  files:
    - test_jaxlib.py
  requires:
    - pip
  imports:
    - jaxlib
    # Only this import actually triggers the load of XLA
    - jaxlib.xla_client
  commands:
    - pip check
    - python test_jaxlib.py
    # ensure that the package metadata did not mangle in the git hash, see #274
    - test -f $SP_DIR/jaxlib-{{ version }}.dist-info/METADATA

about:
  home: http://github.com/jax-ml/jax
  license: Apache-2.0
  license_file: LICENSE
  summary: 'Composable transformations of Python+NumPy programs: differentiate, vectorize, JIT to GPU/TPU, and more'
  dev_url: http://github.com/jax-ml/jax

extra:
  recipe-maintainers:
    - ehfd
    - ericmjl
    - xhochy
    - ngam
    - h-vetinari
