{% set version = "0.1.55" %}
{% set name = "jaxlib" %}

# compute right wheel filename for later
{% set pyver = "cp{}{}".format(PY_VER[0], PY_VER[2]) %}
{% set platform = "manylinux2010_x86_64" %}  # [linux]
{% set platform = "macosx_10_9_x86_64" %}  # [osx]
# {distribution}-{version}(-{build tag})?-{python tag}-{abi tag}-{platform tag}.whl.
{% set fn = "{}-{}-{}-none-{}.whl".format(name, version, pyver, platform) %}

# only use these for the URLS to help the bot
# the urls below have to be explicit for the bot to work
{% set linux_whl = "manylinux2010_x86_64" %}
{% set osx_whl = "macosx_10_9_x86_64" %}

package:
  name: jaxlib
  version: {{ version }}

source:
  fn: wheel.whl

  url: https://pypi.io/packages/cp36/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}-cp36-none-{{ linux_whl }}.whl  # [linux and py==36]
  sha256: f572f78501e95c6210af44a80289f30a53200e80f200cab625b2b065493750a3  # [linux and py==36]
  url: https://pypi.io/packages/cp36/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}-cp36-none-{{ osx_whl }}.whl  # [osx and py==36]
  sha256: 725bf7912fd2789fd5b89fd0caa96fbf1504bdc144e7e3ce799bdb19bd2afdbb  # [osx and py==36]

  url: https://pypi.io/packages/cp37/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}-cp37-none-{{ linux_whl }}.whl  # [linux and py==37]
  sha256: 0aefe4dfed5c4a1d9482d845780567a53c555e6e7ad618ec87999e36e28d390f  # [linux and py==37]
  url: https://pypi.io/packages/cp37/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}-cp37-none-{{ osx_whl }}.whl  # [osx and py==37]
  sha256: 75382b616f47a825f60969bf3594750ce22dbb9b98ac064bed938977a7c0f217  # [osx and py==37]

  url: https://pypi.io/packages/cp38/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}-cp38-none-{{ linux_whl }}.whl  # [linux and py==38]
  sha256: 2fb35969be8cba8aa4772ba682006ab3452b481d771ed4e9257bd78d4046f7fa  # [linux and py==38]
  url: https://pypi.io/packages/cp38/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}-cp38-none-{{ osx_whl }}.whl  # [osx and py==38]
  sha256: 319fe83080be379477bda491d04d44b19099531d0a914916c2359e0d5806f845  # [osx and py==38]

build:
  number: 1
  skip: true  # [win or py2k]
  script:
    - mv wheel.whl {{ fn }}
    - {{ PYTHON }} -m pip install --no-deps -vv {{ fn }}

requirements:
  host:
    - python
    - pip
  run:
    - python
    - absl-py
    - numpy >=1.12
    - protobuf >=3.6.0
    - scipy
    - six

test:
  requires:
    - pip
  commands:
    - pip check
  # imports:
    # cannot run the test b/c this is not really manylinux1 GLIBC_2.14
    # Google :-/
    # - jaxlib

about:
  home: http://github.com/google/jax
  license: Apache-2.0
  license_file: LICENSE
  summary: 'Composable transformations of Python+NumPy programs: differentiate, vectorize, JIT to GPU/TPU, and more'

  dev_url: http://github.com/google/jax

extra:
  recipe-maintainers:
    - ericmjl
