{% set version = "0.4.15" %}
{% set number = 1 %}

{% if cuda_compiler_version != "None" %}
{% set number = number + 200 %}
{% endif %}


package:
  name: jaxlib
  version: {{ version }}

source:
  # only pull sources after upstream PyPI release...
  url: https://github.com/google/jax/archive/jaxlib-v{{ version }}.tar.gz
  sha256: d89e25cab6fc2b5e0cbde2ade0963272fa98b00167b0b8aca0516a0af9befca2
  patches:
    - patches/0001-custom-build.diff
    - patches/0002-bazelrc-edit.diff  # [cuda_compiler_version == "11.2"]

build:
  number: {{ number }}
  skip: true  # [win or py<39]
  skip: true  # [cuda_compiler_version in ("10.2", "11.0", "11.1")]
  string: cuda{{ cuda_compiler_version | replace('.', '') }}py{{ CONDA_PY }}h{{ PKG_HASH }}_{{ PKG_BUILDNUM }}  # [cuda_compiler_version != "None"]
  string: cpu_py{{ CONDA_PY }}h{{ PKG_HASH }}_{{ PKG_BUILDNUM }}  # [cuda_compiler_version == "None"]

requirements:
  build:
    - {{ compiler('c') }}
    - {{ compiler('cxx') }}
    - {{ compiler('cuda') }}                 # [cuda_compiler_version != "None"]
    - python                                 # [build_platform != target_platform]
    - cross-python_{{ target_platform }}     # [build_platform != target_platform]
    - numpy                                  # [build_platform != target_platform]
    - unzip
    # Keep bazel listed twice here to help the migrators track dependencies
    - bazel
    - bazel >=5.1.1,<6
    - bazel-toolchain
    # need protoc
    - libprotobuf
    # needs protoc-gen-grpc
    - libgrpc
    # needs flatc
    - flatbuffers <2.0.6
    # list libabseil here to ensure pinning correctly
    - libabseil
  host:
    - cudnn      # [cuda_compiler_version != "None"]
    - nccl       # [cuda_compiler_version != "None"]
    - python
    - pip
    - numpy
    - wheel
    # avoid not being able to pass `-C=--build-option=--python-tag=cp<x>` due to
    # https://github.com/pypa/build/issues/202, which is being used by jaxlib in
    # https://github.com/google/jax/blame/jaxlib-v0.4.15/jaxlib/tools/build_wheel.py
    - python-build <1
    # list libabseil here to ensure pinning correctly
    - libabseil
    - flatbuffers <2.0.6
    - libgrpc
    - openssl
    - zlib
  run:
    - python
    - {{ pin_compatible('numpy') }}
    - scipy >=1.7
    - ml_dtypes >=0.2.0
    - __cuda  # [cuda_compiler_version != "None"]
  run_constrained:
    - jax >={{ version }}
    - __osx >={{ MACOSX_DEPLOYMENT_TARGET|default("10.9") }}  # [osx]

test:
  files:
    - test_jaxlib.py
  requires:
    - pip
  commands:
    - pip check
    - python test_jaxlib.py
  imports:
    - jaxlib
    # Only this import actually triggers the load of XLA
    - jaxlib.xla_client

about:
  home: http://github.com/google/jax
  license: Apache-2.0
  license_file: LICENSE
  summary: 'Composable transformations of Python+NumPy programs: differentiate, vectorize, JIT to GPU/TPU, and more'
  dev_url: http://github.com/google/jax

extra:
  recipe-maintainers:
    - ericmjl
    - xhochy
    - ngam
