{% set version = "0.4.38" %}
{% set build = 0 %}

{% if cuda_compiler_version != "None" %}
{% set build = build + 200 %}
{% endif %}


package:
  name: jaxlib
  version: {{ version }}

source:
  # only pull sources after upstream PyPI release...
  url: https://github.com/google/jax/archive/jax-v{{ version }}.tar.gz
  sha256: ca1e63c488d505b9c92e81499e8b06cc1977319c50d64a0e58adbd2dae1a625c
  patches:
    - patches/0001-Allow-for-custom-CUDA-build.patch
    - patches/0002-Consolidated-build-fixes-for-XLA.patch
    # cannot absorb this into the overall xla patch, because patching three vendored projects
    # deep breaks the application of the patch using `patch` (presumably due to lines starting
    # legitimately with `+++` being misinterpreted as a hunk separator).
    # - patches/0007-xla-cpu-Fix-build-errors-from-ACL.patch
    - patches/0003-fix-member-access-to-packed-CUDA-struct.patch
    - patches/0004-fix-an-ambiguous-type.patch

build:
  number: {{ build }}
  skip: true  # [win or py<310]
  skip: true  # [cuda_compiler != "None" and aarch64]
  # Currently the GPU kernels (and their abseil includes) are not compatible with GCC 11
  skip: true  # [cuda_compiler_version == "11.8"]
  string: cuda{{ cuda_compiler_version | replace('.', '') }}py{{ CONDA_PY }}h{{ PKG_HASH }}_{{ PKG_BUILDNUM }}  # [cuda_compiler_version != "None"]
  string: cpu_py{{ CONDA_PY }}h{{ PKG_HASH }}_{{ PKG_BUILDNUM }}  # [cuda_compiler_version == "None"]

requirements:
  build:
    - {{ compiler('c') }}
    - {{ stdlib("c") }}
    - {{ compiler('cxx') }}
    - {{ compiler('cuda') }}                 # [cuda_compiler_version != "None"]
    - python                                 # [build_platform != target_platform]
    - cross-python_{{ target_platform }}     # [build_platform != target_platform]
    - numpy                                  # [build_platform != target_platform]
    - zlib                                   # [build_platform != target_platform]
    - unzip
    - rsync  # [(cuda_compiler_version or "").startswith("12")]
    # Keep bazel listed twice here to help the migrators track dependencies
    - bazel
    - bazel 6.*
    - bazel-toolchain >=0.1.10
    # need protoc
    - libprotobuf
    # needs protoc-gen-grpc
    - libgrpc
    # needs flatc
    - flatbuffers <2.0.6
    # list libabseil here to ensure pinning correctly
    - libabseil
    - sed
  host:
    - cudnn             # [cuda_compiler_version != "None"]
    - nccl              # [cuda_compiler_version != "None"]
    - cuda-cupti-dev    # [(cuda_compiler_version or "").startswith("12")]
    - cuda-cudart-dev   # [(cuda_compiler_version or "").startswith("12")]
    - cuda-nvml-dev     # [(cuda_compiler_version or "").startswith("12")]
    - cuda-nvtx-dev     # [(cuda_compiler_version or "").startswith("12")]
    - cuda-nvcc-tools  # [(cuda_compiler_version or "").startswith("12")]
    - libcublas-dev     # [(cuda_compiler_version or "").startswith("12")]
    - libcusolver-dev   # [(cuda_compiler_version or "").startswith("12")]
    - libcurand-dev     # [(cuda_compiler_version or "").startswith("12")]
    - libcufft-dev      # [(cuda_compiler_version or "").startswith("12")]
    - libcusparse-dev   # [(cuda_compiler_version or "").startswith("12")]
    - python
    - pip
    - numpy
    - setuptools
    - wheel
    - cuda-version {{ cuda_compiler_version }}  # [cuda_compiler_version != "None"]
    # avoid not being able to pass `-C=--build-option=--python-tag=cp<x>` due to
    # https://github.com/pypa/build/issues/202, which is being used by jaxlib in
    # https://github.com/google/jax/blame/jaxlib-v0.4.15/jaxlib/tools/build_wheel.py
    - python-build <1
    # list libabseil here to ensure pinning correctly
    - libabseil
    - flatbuffers <2.0.6
    - libgrpc
    - openssl
    - zlib
  run:
    - python
    - scipy >=1.9
    - ml_dtypes >=0.2.0
    - __cuda  # [cuda_compiler_version != "None"]
    - cuda-nvcc-tools  # [(cuda_compiler_version or "").startswith("12")]
    # Workaround for https://github.com/conda-forge/jaxlib-feedstock/pull/288#issuecomment-2511925904
    - libcublas-dev     # [(cuda_compiler_version or "").startswith("12")]
    - libcusolver-dev   # [(cuda_compiler_version or "").startswith("12")]
    - libcurand-dev     # [(cuda_compiler_version or "").startswith("12")]
    - cuda-cupti-dev    # [(cuda_compiler_version or "").startswith("12")]
    - libcufft-dev      # [(cuda_compiler_version or "").startswith("12")]
    - libcusparse-dev   # [(cuda_compiler_version or "").startswith("12")]
  run_constrained:
    - jax >={{ version }}

test:
  files:
    - test_jaxlib.py
  requires:
    - pip
  imports:
    - jaxlib
    # Only this import actually triggers the load of XLA
    - jaxlib.xla_client
  commands:
    - pip check
    - python test_jaxlib.py
    # ensure that the package metadata did not mangle in the git hash, see #274
    - test -f $SP_DIR/jaxlib-{{ version }}.dist-info/METADATA

about:
  home: http://github.com/google/jax
  license: Apache-2.0
  license_file: LICENSE
  summary: 'Composable transformations of Python+NumPy programs: differentiate, vectorize, JIT to GPU/TPU, and more'
  dev_url: http://github.com/google/jax

extra:
  recipe-maintainers:
    - ericmjl
    - xhochy
    - ngam
    - h-vetinari
