provider:
   linux_aarch64: azure
   linux_ppc64le: azure
azure:
  store_build_artifacts: true
bot:
  automerge: true
build_platform:
  osx_arm64: osx_64
  linux_aarch64: linux_64
  linux_ppc64le: linux_64
conda_forge_output_validation: true
github:
  branch_name: main
  tooling_branch_name: main
test_on_native_only: true
remote_ci_setup:
   - conda-forge-ci-setup=3
   - conda-forge/label/lief_dev::py-lief
   - conda-forge/label/lief_dev::liblief
